name: UET Auction CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-test-checkstyle:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Clone ma nguon
      uses: actions/checkout@v4

    - name: 2. Cai dat Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: 3. Chay Checkstyle
      run: mvn checkstyle:check

    - name: 4. Chay Unit Test
      run: mvn test

    - name: 5. Build du an
      run: mvn package -DskipTests
